import LegalPage from '../../components/LegalPage';

export default function PrivacyPolicyPage() {
  return <LegalPage eyebrow="Privacy" title="Privacy Policy" intro="This policy explains how LegalSync collects, uses, stores, and protects information when you visit our website or use our calendar synchronization service." sections={[
    { title: 'Information we receive', paragraphs: ['We receive information you provide when you create an account, contact support, start a trial, or connect an external service. This may include your name, work email, firm details, login credentials, billing status, and support messages.', 'When you authorize Clio, Google Calendar, or Microsoft Outlook, we receive only the information and permissions needed to provide the connection and synchronization features you select.'] },
    { title: 'How we use information', paragraphs: ['We use information to provide, secure, maintain, and improve LegalSync; authenticate users; synchronize authorized calendars; process subscriptions; respond to support requests; and communicate service or security updates.', 'We do not sell personal information. We use aggregated or de-identified information for analytics and product improvement where practical.'] },
    { title: 'Sharing and service providers', paragraphs: ['We share information with vendors that help us host the service, send email, process payments, monitor reliability, and provide integrations. These providers may process information only to perform services for LegalSync and under appropriate contractual protections.', 'We may disclose information when required by law, to protect users or the service, or as part of a merger, acquisition, or business transfer.'] },
    { title: 'Retention and your choices', paragraphs: ['We retain information for as long as needed to provide the service, meet legal and accounting obligations, resolve disputes, and enforce agreements. You may request access, correction, export, or deletion by contacting privacy@legalsync.com. Some records may need to be retained for legal or security reasons.'] },
    { title: 'Security and changes', paragraphs: ['We use reasonable administrative, technical, and organizational safeguards, including HTTPS/TLS, access controls, and protected secret storage. No online service can guarantee absolute security.', 'We may update this policy as the service changes. We will post the revised version here and update the date above.'] },
  ]} />;
}